version: '3.1'
services:
  stats-server:
    build: stat-service/stat-server
    image: stat-server
    container_name: stat-server
    ports:
      - "8080:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=4315
    - TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stats-db
    ports:
    - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4315

  ewm-service:
    build: stat-service/ewm-http-client
    image: ewm-http-client
    container_name: http-client
    ports:
      - "9090:9090"
    environment:
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-db
    ports:
      - "6555:5532"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4315
